name: Example workflow for Node using Snyk 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master  
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high	
    - name: Upload result to GitHub Code Scanning
      run : ls -la
      run : npm install -g snyk
      run : snyk config set api= ${{ secrets.SNYK_TOKEN }}
      run : snyk test
    

